  - name: play level variables
    hosts: localhost
    vars:
      URL: the.example.com
    tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: url is {{ URL }}

  - name : vars from files
      hosts : localhost
      vars_file :
      - demo-vars.yml
      tasks :
      - name : print URL
        ansible.builtin.debug :
          msg : url is {{ URL }}
