- name: demo for loops
  hosts: localhost
  tasks:
  - name: loop through list
    debug:
      msg: fruit = {{item}}
      # list item are accessed by fact variable item
    loop:
      - apple
      - orange
  - name: loops through maps
    debug:
      msg: fruit name = {{item.name}}, quantity = {{item.quantity}}
    loop:
      - {name: apple, quantity: 10}
      - {name: orange, quantity: 30}