- name: play level variables
  hosts: localhost
  vars:
    URL: the.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: url is {{ URL }}

- name: task level variables
  hosts: localhost
  tasks:
  - name: print URL
    ansible.builtin.debug:
      msg: url is {{ URL }}
    vars :
      URL : task.example.com

- name: inventory level variables
  hosts: localhost
  tasks:
    - name: print URL
      ansible.builtin.debug:
        #msg: url is {{ URL }}

- name : fact & magic level variables
  hosts : localhost
  tasks :
  - name : print hostname
    ansible.builtin.debug :
      msg : hostname is {{ ansible_hostname }} menory {{ansible_memory_mb.real.free}}
